name = "ex02-service-caller"
main = "src/caller.ts"
compatibility_date = "2024-09-23"

[[services]]
binding = "AUTH"
service = "ex02-auth-worker"

[[workers]]
name = "ex02-auth-worker"
main = "src/auth.ts"
