// Auto-generated by scripts/sync-examples.ts. Do not edit.
// Mirrors cloudflare/workers-sdk's top-level vitest.shared.ts so that the
// fixtures under examples/upstream/<name>/vitest.config.mts (which import
// `../../vitest.shared`) can be loaded outside of the upstream pnpm workspace.
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		reporters: ["default"],
		testTimeout: 50_000,
		hookTimeout: 50_000,
		teardownTimeout: 50_000,
		restoreMocks: true,
		retry: 1,
	},
});
